### ISSUE TITLE
Tupperhook

### ISSUE THREAD

**Issue by Azuranaito** [Keterr/Tupperbox#107]
There's an issue where all the web hooks from different users are all addressed as Tupperhook. This just happened today and because the web hooks are all the same name, messages from different web hooks are sent under the wrong web hook.

**Comment by JaytheJoker** [comment]
I have the same issue.

**Comment by Keterr** [comment]
duplicate #106

**Comment by Azuranaito** [comment]
I just want to know how it could be fixed

**Comment by Keterr** [comment]
read #106
