### ISSUE TITLE
Issues with Members Using Tuppers

### ISSUE THREAD

**Issue by carrotdraig** [Keterr/Tupperbox#114]
I'm new to Tupperbox and have been making a few tuppers for members on my server to use. Upon asking them to try using tuppers, none of them are able to use them but me (I am the server owner). I've messed with different roles to see what works, but nothing is working.

**Comment by Keterr** [comment]
Created tuppers are saved to your user account, not to the server. Other members in the server will have to make an identical tupper, or import tuppers exported using `tul!export`.

**Comment by carrotdraig** [comment]
I see, thank you much!
