### ISSUE TITLE
Replies are not proxied

### ISSUE THREAD

**Issue by Qyriad** [Keterr/Tupperbox#115]
Discord recently added the ability to [reply to posts](https://support.discord.com/hc/en-us/articles/360057382374-Replies-FAQ), but the reply status of a message is lost when proxied through Tupperbox. This is best illustrated with screenshots:
![Screenshot from 2020-12-05 16-55-03](https://user-images.githubusercontent.com/1542224/101267873-e8d6ca00-371a-11eb-8527-c71ddf026214.png)
![Screenshot from 2020-12-05 16-55-21](https://user-images.githubusercontent.com/1542224/101267875-ec6a5100-371a-11eb-8511-105cd217f7f5.png)

**Comment by dev-kittens** [comment]
Unfortunately, webhooks cannot currently send replies. There is a feature request for that [on Discord's API repo](https://github.com/discord/discord-api-docs/issues/2251)

**Comment by Qyriad** [comment]
Dammit. Alright. Hopefully they add it soon.

**Comment by Keterr** [comment]
A sort of bootleg version of this is now implemented on the main bot.
