### ISSUE TITLE
Add command to edit proxied messages

### ISSUE THREAD

**Issue by Qyriad** [Keterr/Tupperbox#117]
The Discord API now allows [editing webhook messages](https://github.com/discord/discord-api-docs/issues/1544#issuecomment-708707645). Eris has an open PR for adding support for this: abalabahaha/eris#1060, but as you can see, it hasn't been merged yet. However, the code for it is trivial, and could easily be implemented in Tupperbox in the meantime. 

My javascript is extremely rusty, but here's a working example command that just accepts a message ID and the new content string:

```js
// commands/edit.js

// Reimplemented from eris/lib/rest/Endpoints.js.
const WEBHOOK_MESSAGE = (hookID, token, msgID) => `/webhooks/${hookID}/${token}/messages/${msgID}`;

module.exports = {
	help: cfg => "Edit a proxied message.",
	usage: cfg => ["edit [message id] [new message]"],
	permitted: () => true,
	cooldown: msg => 1500,
	execute: async (bot, msg, args, _cfg, _members, _ng = false) => {

		// Get the ID of the proxied message to edit.
		const id = args[0];

		// Get the new content of the message.
		const content = args.slice(1).join(' ');

		// Get the endpoint URL for the webhook for that message.
		const hook = await bot.proxy.fetchWebhook(bot, msg.channel);
		const url = WEBHOOK_MESSAGE(hook.id, hook.token, id);

		// Perform the actual request.
		await bot.requestHandler.request("PATCH", url, false, {
			wait: true,
			content: content
		});
	}
}

```

I can PR an implementation, but I don't know how the user-facing interface should look, unless the code above (with some error handling) is sufficient.

**Comment by greysdawn** [comment]
This repository is no longer maintained at the moment due to the bot moving to be closed source, but webhook/proxy editing is a planned feature once a user-friendly workflow has been figured out

**Comment by Qyriad** [comment]
I didn't realize the bot was moving to closed source. That's pretty disappointing to hear :/

**Comment by Keterr** [comment]
This feature is now live on the main bot.
