### ISSUE TITLE
Not Detecting .env

### ISSUE THREAD

**Issue by MissCupcake9** [Keterr/Tupperbox#65]
I entered all the info needed in .env and i keep getting that error https://pastebin.com/Mw0ZaX3C
idk whats the issue and im also having issue with the modul if i could get some help it would be nice
thanks in advance!

**Comment by Keterr** [comment]
`dotenv` is included in the package dependencies. Please make sure you run `npm install` per the install instructions.

**Comment by MissCupcake9** [comment]
> `dotenv` is included in the package dependencies. Please make sure you run `npm install` per the install instructions.

well im getting errors is it normal im also on windows and trying to run the bot off my computer on localhost here the log from the npm install been 3 time ive ran it https://pastebin.com/1EyHJeJE

**Comment by Keterr** [comment]
The install log is riddled with errors. The top one says Git isn't installed, so you'll need to install that. Please join the support server if further assistance is needed: https://discord.gg/rHxMbt2

**Comment by MissCupcake9** [comment]
alright thank you!
