### ISSUE TITLE
Stop button reaction triggers code for jumping to specific page number

### ISSUE THREAD

**Issue by Tristan379** [Keterr/Tupperbox#66]
https://github.com/Keterr/Tupperbox/blob/rewrite/events/messageReactionAdd.js
There should be a `break;` at the end of the stop button's case(lines 52-59). And since the main function of that button is currently commented out, it's actually just overflowing down into the next button's code where previously it would have returned something before the missing break and worked fine.

**Comment by Keterr** [comment]
Fixed in dae21e2125d5e4dfcf4309a00af74b8d8db0f8c3
