### ISSUE TITLE
Autoproxy

### ISSUE THREAD

**Issue by ndo360** [Keterr/Tupperbox#71]
Greetings!

I was wondering if it would be possible for a feature to be made that binds a created character to a user. Once bound it replaces all messages from the user with the character they are bound to. (This would allow regular chat flow, and not have to worry about forgetting the prefix.)

Then when finished, they could unbind themselves with a command and they can chat as normal. Would this be possible?

**Comment by dragos240** [comment]
Just putting this out here, but someone has made a pull request for this: https://github.com/Keterr/Tupperbox/pull/98

**Comment by Keterr** [comment]
This is implemented on the live bot.
