### ISSUE TITLE
Not connecting to pgsql

### ISSUE THREAD

**Issue by raxixor** [Keterr/Tupperbox#72]
It gets stuck at `modules/db.js` "(await (await pool.connect()).release());"
I'm assuming it is stuck connecting to postgres, but I can't figure out why. I can connect to postgres from my own machine, from my laptop, but node is failing here.

**Comment by acw0** [comment]
Hi there! It seems this is a bug with NodeJS v14. Any previous versions *should* work.

**Comment by raxixor** [comment]
I updated the postgres package in package.json instead, seemed to do the trick.

**Comment by acw0** [comment]
... oh, that's probably a better idea. I'd recommend submitting a PR for that, if you don't mind.

**Comment by raxixor** [comment]
Done :)
