### ISSUE TITLE
The bot is down?

### ISSUE THREAD

**Issue by IssueDen** [Keterr/Tupperbox#73]
I dont know exactly what happened, but is it down?Or discontinued?

**Comment by hellaskye** [comment]
it's down in my server as well...

**Comment by IssueDen** [comment]
We need ghost to see this.In another server, my friend said it worked fine.But not in ours.This is very confusing.

**Comment by hellaskye** [comment]
ours is back up now!

**Comment by IssueDen** [comment]
Ours isn’t.I’ll see if something happened.

**Comment by IssueDen** [comment]
Its coming back on slowly, I’ll make another report if it doesn’t.
