### ISSUE TITLE
can't do more than one shard

### ISSUE THREAD

**Issue by bobby365** [Keterr/Tupperbox#75]
![Screenshot (39)](https://user-images.githubusercontent.com/58282117/86531633-d872a880-be77-11ea-9df8-13dd5e17a3ef.png)
![Screenshot (40)_LI](https://user-images.githubusercontent.com/58282117/86531677-28ea0600-be78-11ea-92d2-1384d52c9f1d.png)

**Comment by Keterr** [comment]
Heroku is not suitable for clustered sharding. If your bot isn't in more than a few servers, edit `index.js` options to `clusters: 1`.

**Comment by bobby365** [comment]
can you show me where I would find that option

**Comment by bobby365** [comment]
@Keterr
